export const FETCH_SHOTS_START = "FETCH_SHOTS_START";
export const FETCH_SHOTS_SUCCESS = "FETCH_SHOTS_SUCCESS";
export const FETCH_SHOTS_FAILED = "FETCH_SHOTS_FAILED";

export const UPLOAD_SHOTS_START = "UPLOAD_SHOTS_START";
export const UPLOAD_SHOTS_SUCCESS = "UPLOAD_SHOTS_SUCCESS";
export const FETCH_SINGLESHOT_SUCCESS = "FETCH_SINGLESHOT_SUCCESS";
export const UPLOAD_SHOTS_FAILED = "UPLOAD_SHOTS_FAILED";

export const POST_COMMENT_START = "POST_COMMENT_START";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILED = "POST_COMMENT_FAILED";

export const AUTH_START = 'AUTH_START'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const USER_FETCH_START = 'USER_FETCH_START'
export const USER_FETCH_SUCCESS = 'USER_FETCH_SUCCESS'

export const UPDATE_USER_START = 'UPDATE_USER_START'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED'

export const FETCH_COMMENT_START = 'FETCH_COMMENT_START'
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS'
export const FETCH_COMMENT_FAILED = 'FETCH_COMMENT_FAILED'

export const SHOT_LIKED_SUCCESS="SHOT_LIKED_SUCCESS"
export const SHOT_DISLIKED_SUCCESS="SHOT_DISLIKED_SUCCESS"

export const SHOT_UPDATE_START="SHOT_UPDATE_START"
export const SHOT_UPDATE_SUCCESS="SHOT_UPDATE_SUCCESS"
export const SHOT_UPDATE_FAILED="SHOT_UPDATE_FAILED"