import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import Home from '../components/home/Home'
import { getCookie } from 'cookies-next';


export default function App() {
  const router = useRouter()
  useEffect(() => {
    if(getCookie('user')){
      router.push("/netflix")
    }
  },[])
  return (
    <div>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* landing page */}
      <Home/>
    </div>
  )
}
