(function(c,d){function u(c){if(c)return c.replace(/^\s+|\s+$/g,"")}function q(f,d){if(!f)return{};var b="INFO"===d.logLevel;f.m&&f.m.message&&(f=f.m);var g=d.m||d.message||"";g=f.m&&f.m.message?g+f.m.message:f.m&&f.m.target&&f.m.target.tagName?g+("Error handler invoked by "+f.m.target.tagName+" tag"):f.m?g+f.m:f.message?g+f.message:g+"Unknown error";g={m:g,name:f.name,type:f.type,csm:P+" "+(f.fromOnError?"onerror":"ueLogError")};var h,m=0;g.logLevel=d.logLevel||C;d.adb&&(g.adb=d.adb);if(h=d.attribution)g.attribution=
""+h;if(!b){g.pageURL=d.pageURL||""+(window.location?window.location.href:"")||"missing";g.f=f.f||f.sourceURL||f.fileName||f.filename||f.m&&f.m.target&&f.m.target.src;g.l=f.l||f.line||f.lineno||f.lineNumber;g.c=f.c?""+f.c:f.c;g.s=[];g.t=c.ue.d();if((b=f.stack||(f.err?f.err.stack:""))&&b.split)for(g.csm+=" stack",h=b.split("\n");m<h.length&&g.s.length<z;)(b=h[m++])&&g.s.push(u(b));else{g.csm+=" callee";var v=x(f.args||arguments,"callee");for(h=m=0;v&&m<z;){var l=n;v.skipTrace||(b=v.toString())&&b.substr&&
(l=0===h?4*n:l,l=1==h?2*n:l,g.s.push(b.substr(0,l)),h++);v=x(v,"caller");m++}}if(!g.f&&0<g.s.length&&(m=g)&&m.s){var t;b=0<m.s.length?m.s[0]:"";h=1<m.s.length?m.s[1]:"";b&&(t=b.match(y));t&&3==t.length||!h||(t=h.match(O));t&&3==t.length&&(m.f=t[1],m.l=t[2])}}return g}function x(c,d){try{return c[d]}catch(b){}}function w(f,v){if(f){for(var b=q(f,v),g=(window.ue_err?window.ue_err.errorHandlers:null)||[],h=0;h<g.length;h++)"function"==typeof g[h].handler&&g[h].handler(b);c.ue.log(b,v.channel||l,{nb:1});
"function"===typeof ue_err.elh&&ue_err.elh(f,v);try{if(!f.fromOnError){var m=d.console,n=d.JSON;g="Error logged with the Track\x26Report JS errors API(http://tiny/1covqr6l8/wamazindeClieUserJava): ";if(m){if(n&&n.stringify)try{g+=n.stringify(b)}catch(N){g+="no info provided; converting to string failed"}else g+=b.m;"function"===typeof m.error?m.error(g,b):"function"===typeof m.log&&m.log(g,b)}}}catch(N){}}}function D(f,d){if(f&&!(c.ue_err.ec>c.ue_err.mxe)){c.ue_err.ter.push(f);d=d||{};var b=f.logLevel||
d.logLevel;d.logLevel=b;d.attribution=f.attribution||d.attribution;b&&b!==C&&b!==K&&b!==E&&b!==L||c.ue_err.ec++;b&&b!=C||ue_err.ecf++;w(f,d)}}if(c.ue_err&&(!c.ueLogError||c.ueLogError.isStub)){var l=c.ue_err_chan||"jserr",C="FATAL",K="ERROR",E="WARN",L="DOWNGRADED",P="v5",z=20,n=256,O=/\(?([^\s]*):(\d+):\d+\)?/,y=/.*@(.*):(\d*)/;w.skipTrace=1;q.skipTrace=1;D.skipTrace=1;(function(){if(c.ue_err.erl){var f=c.ue_err.erl.length,d;for(d=0;d<f;d++){var b=c.ue_err.erl[d];w(b.ex,b.info)}ue_err.erl=[]}})();
c.ueLogError=D}})(ue_csm,window);
(function(c,d){function u(a){for(var k={},e,p,B=0;B<a.length;B++)p=a[B],p.r=p.r||b.rid,p.s=p.s||c.ue_sid,e=p.r+p.s+p.m,p.c&&(k[e]||(k[e]=[]),k[e].push(a[B]));return k}function q(a){for(var k=1;k<arguments.length;k++){var e=arguments[k];try{if(e.isSupported)return e.send(a)}catch(p){}}}function x(){if(h.length&&!b.paused){for(var a=0;a<A.length;a++)A[a]();b._flhs+=1;w();q(u(h.splice(0,h.length)),F,G,H)}t=M=0}function w(){n&&D({k:"chk",f:b._flhs,l:b._lpn,s:"full"},"csm")}function D(a,k,e){e=e||{};!c.ue_furl||
0===e.bf&&b.isBF||(a={r:e.r||(b.paused?void 0:b.rid),s:e.s||(b.paused?void 0:c.ue_sid),m:e.m||c.ue_mid,mkt:e.mkt||c.ue_mkt,sn:e.sn||c.ue_sn,c:k,d:a,t:e.t||b.d(),cs:e.c&&c.ue_qsl},b._lpn[k]=(b._lpn[k]||0)+1,e.b?q(u([a]),F,H):e.nb?q(u([a]),F,G,H):e.img||Q[k]?q(u([a]),H):e.ff?(h.push(a),x()):e.n?(h.push(a),0===I?x():t||(t=d.setTimeout(x,I))):(h.push(a),M||(M=d.setTimeout(x,R))))}function l(a,k,e){J++;J==z&&D({m:"Max number of Forester Logs exceeded",f:"forester-client.js",logLevel:"ERROR"},d.ue_err_chan||
"jserr");(J<z||e&&e.il)&&D(a,k,e)}function C(){if(!N){for(var a=0;a<m.length;a++)m[a]();for(a=0;a<A.length;a++)A[a]();b._flhs+=1;w();q(u(h.splice(0,h.length)),F,H);N=!0}}function K(a){var k=f(a);a.reqs&&(k={csmcount:{counter:O,t:0,value:k.length}},k.csmcount.value+=f(k).length,a.reqs.push(k),k=f(a));return k}var E={};(function(){function a(a){return 10>a?"0"+a:a}function k(a){b.lastIndex=0;return b.test(a)?'"'+a.replace(b,function(a){var e=d[a];return"string"===typeof e?e:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+
'"':'"'+a+'"'}function e(a,b){var p,B=c,d=b[a];d&&"object"===typeof d&&"function"===typeof d.toJSON&&(d=d.toJSON(a));"function"===typeof g&&(d=g.call(b,a,d));switch(typeof d){case "string":return k(d);case "number":return isFinite(d)?String(d):"null";case "boolean":case "null":return String(d);case "object":if(!d)return"null";c+=f;var r=[];if("[object Array]"===Object.prototype.toString.apply(d)){b=d.length;for(a=0;a<b;a+=1)r[a]=e(a,d)||"null";var h=0===r.length?"[]":c?"[\n"+c+r.join(",\n"+c)+"\n"+
B+"]":"["+r.join(",")+"]";c=B;return h}if(g&&"object"===typeof g)for(b=g.length,a=0;a<b;a+=1)"string"===typeof g[a]&&(p=g[a],(h=e(p,d))&&r.push(k(p)+(c?": ":":")+h));else for(p in d)Object.prototype.hasOwnProperty.call(d,p)&&(h=e(p,d))&&r.push(k(p)+(c?": ":":")+h);h=0===r.length?"{}":c?"{\n"+c+r.join(",\n"+c)+"\n"+B+"}":"{"+r.join(",")+"}";c=B;return h}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(e){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+
1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var b=/[\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,f,d={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},g;"function"!==typeof E.stringify&&(E.stringify=function(a,
b,k){var d;f=c="";if("number"===typeof k)for(d=0;d<k;d+=1)f+=" ";else"string"===typeof k&&(f=k);if((g=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return e("",{"":a})})})();var L=function(){function a(b,e){if(null==b)return e.push("!n");if("number"===typeof b)return e.push("!"+b);if("string"===typeof b)return"\\"==b[b.length-1]?e.push("'"+b.replace(/'/g,"\\'")+"u005C'"):e.push("'"+b.replace(/'/g,"\\'")+"'");if("boolean"===typeof b)return e.push(b?
"!t":"!f");if(b instanceof Array){e.push("*");for(var c=0;c<b.length;c++)a(b[c],e);return e.push(")")}if("object"==typeof b){e.push("(");for(c in b)b.hasOwnProperty(c)&&(e.push(c),a(b[c],e));return e.push(")")}return e.push("!n")}return{stringify:function(b){var e=[];a(b,e);return e.join("")}}}(),P=c.ue_qsl||2E3,z=2E3,n=1===window.ue_ddq,O="foresterPayloadSize",y=function(){},f=d.JSON&&d.JSON.stringify||E&&E.stringify,v=L.stringify,b=c.ue||{};L=c.uet||y;(c.uet||y)("bb","ue_frst_v2",{wb:1});var g=
"//"+c.ue_furl+"/1/batch/1/OE/",h=[],m=[],A=[],N=!1,t,M,I=void 0===c.ue_hpfi?1E3:c.ue_hpfi,R=void 0===c.ue_lpfi?1E4:c.ue_lpfi,Q={"scheduled-delivery":1},J=0,G=function(){function a(){if(d.XDomainRequest){var a=new XDomainRequest;a.onerror=y;a.ontimeout=y;a.onprogress=y;a.onload=y;a.timeout=0;return a}if(d.XMLHttpRequest){a=new XMLHttpRequest;if(!("withCredentials"in a))throw"";return a}if(d.ActiveXObject){for(var b=0;b<f.length&&!a;b++)try{a=new ActiveXObject(f[b]),f=[f[b]]}catch(S){}return a}}function k(a){for(var e=
[],d=a[0]||{},k=0;k<a.length;k++){var f={};f[a[k].c]=a[k].d;e.push(f)}return{rid:d.r||b.rid,sid:d.s||c.ue_sid,mid:d.m||c.ue_mid,mkt:d.mkt||c.ue_mkt,sn:d.sn||c.ue_sn,reqs:e}}function e(b){var e=k(b),c=a();if(!c)throw"";c.onerror=function(){for(var a=0;a<b.length;a++)h.push(b[a]);G.isSupported=!1};c.open("POST",g,!0);c.setRequestHeader&&c.setRequestHeader("Content-type","text/plain");e=K(e);c.send(e)}var f="MSXML2.XMLHTTP.6.0 MSXML2.XMLHTTP.5.0 MSXML2.XMLHTTP.4.0 MSXML2.XMLHTTP.3.0 MSXML2.XMLHTTP Microsoft.XMLHTTP".split(" ");
return{send:function(a){for(var b in a)a.hasOwnProperty(b)&&a[b].length&&e(a[b])},buildPOSTBodyLog:k,isSupported:!0}}(),H=function(){return{send:function(a){for(var d in a)if(a.hasOwnProperty(d)){for(var e=a[d],p=e,h={},r,m=0;m<p.length;m++)r=p[m].c,h[r]||(h[r]=[]),h[r].push(p[m]);e=e[0]||{};p=e.sn||c.ue_sn;e=g+(e.m||c.ue_mid)+":"+(e.s||c.ue_sid)+":"+(e.r||b.rid)+(p?":"+p:"");p=[];r=e;m=[];var n=void 0;for(n in h)if(h.hasOwnProperty(n))for(var l=0;l<h[n].length;l++){var t=h[n][l],q=encodeURIComponent((t.cs?
v:f)(t.d));m.push({l:q,t:t.t,p:1,c:n,d:t.cs?"c":"j"})}h=m;m=void 0;n="$";for(t=0;t<h.length;){l=h[t];m!=l.c?(r+=n+l.c+"\x3d",n="\x26",m=l.c):r+=",";q=r;var w=l.d+":",u=l;r=(u.l.match(".{1,"+(P-r.length)+"}[^%]{0,2}")||[])[0]||"";u.l=u.l.substr(r.length);r=q+(w+r+":"+l.t);if(l.l)r+=":"+l.p++ +"_",p.push(r),r=e,n="$",m=0;else if(t++,1!=l.p)for(r+=":"+l.p+"_"+l.p,q=0;q<l.p-1;q++)p[p.length-q-1]+=l.p}p.push(r);e=p;for(p=0;p<e.length;p++)(new Image).src=e[p]}},isSupported:!0}}(),F=function(){return{send:function(a){for(var b in a)if(a.hasOwnProperty(b)){var e=
G.buildPOSTBodyLog(a[b]);e=K(e);if(!navigator.sendBeacon(g,e))throw"";}},isSupported:!!navigator.sendBeacon}}();b._fic=H;b._fac=G;b._fbc=F;b._flq=h;b.sid=b.sid||c.ue_sid;b.mid=b.mid||c.ue_mid;b.furl=b.furl||c.ue_furl;b.sn=b.sn||c.ue_sn;b._flhs=b._flhs||0;b._lpn=b._lpn||{};try{d.amznJQ&&d.amznJQ.declareAvailable&&d.amznJQ.declareAvailable("forester-client"),d.P&&d.P.register&&d.P.register("forester-client",y)}catch(a){c.ueLogError(a,{logLevel:"WARN"})}(function(){b.log&&b.log.isStub&&(b.log.replay(function(a,
b,e){var c=a[2]||{};c.t=b;c.r=e;c.n=1;l(a[0],a[1],c)}),b.onunload.replay(function(a){m.push(a[0])}),b.onflush.replay(function(a){A.push(a[0])}))})();b.log=l;b.log.reset=function(){J=0};b.onunload=function(a){m.push(a)};b.onflush=function(a){A.push(a)};b.attach("beforeunload",C);b.attach("pagehide",C);L("ld","ue_frst_v2",{wb:1})})(ue_csm,window);
ue_csm.ue.exec(function(c,d){var u=function(){},q=function(){return{send:function(c,q){if(q&&c){if(d.XDomainRequest){var l=new XDomainRequest;l.onerror=u;l.ontimeout=u;l.onprogress=u;l.onload=u;l.timeout=0}else if(d.XMLHttpRequest){if(l=new XMLHttpRequest,!("withCredentials"in l))throw"";}else l=void 0;if(!l)throw"";l.open("POST",c,!0);l.setRequestHeader&&l.setRequestHeader("Content-type","text/plain");l.send(q)}},isSupported:!0}}(),x=function(){return{send:function(d,q){if(d&&q)if(navigator.sendBeacon(d,
q))c.ue_sbuimp&&c.ue&&c.ue.ssw&&c.ue.ssw("eelsts","scs");else throw"";},isSupported:!!navigator.sendBeacon&&!(d.cordova&&d.cordova.platformId&&"ios"==d.cordova.platformId)}}();c.ue._ajx=q;c.ue._sBcn=x},"Transportation-clients")(ue_csm,window);
ue_csm.ue.exec(function(c,d){function u(){for(var a=0;a<arguments.length;a++){var c=arguments[a];try{if(c.isSupported){var e=F.buildPayload(h,b);var g=c.send(f,e)}else throw dummyException;return g}catch(B){}}O({m:"All supported clients failed",attribution:"CSMSushiClient_TRANSPORTATION_FAIL",f:"sushi-client.js",logLevel:"ERROR"},d.ue_err_chan||"jserr")}function q(){if(b.length){for(var a=0;a<I.length;a++)I[a]();u(n._sBcn||{},n._ajx||{});b=[];g={};h={};Q=J=m=A=0}}function x(){var a=new Date,b=function(a){return 10>
a?"0"+a:a};return Date.prototype.toISOString?a.toISOString():a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"."+String((a.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}function w(a){try{return JSON.stringify(a)}catch(k){}return null}function D(a,f,e,g){var h=!1;g=g||{};t++;t==E&&O({m:"Max number of Sushi Logs exceeded",f:"sushi-client.js",logLevel:"ERROR",attribution:"CSMSushiClient_MAX_CALLS"},d.ue_err_chan||
"jserr");var k;if(k=!(t>=E))(k=a&&-1<a.constructor.toString().indexOf("Object")&&f&&-1<f.constructor.toString().indexOf("String")&&e&&-1<e.constructor.toString().indexOf("String"))||N++;k&&(n.count&&n.count("Event:"+e,1),a.producerId=a.producerId||f,a.schemaId=a.schemaId||e,a.timestamp=x(),f=Date.now?Date.now():+new Date,e=Math.random().toString().substring(2,12),a.messageId=c.ue_id+"-"+f+"-"+e,g&&!g.ssd&&(a.sessionId=a.sessionId||c.ue_sid,a.requestId=a.requestId||c.ue_id,a.obfuscatedMarketplaceId=
a.obfuscatedMarketplaceId||c.ue_mid),(f=w(a))?(f=f.length,(b.length==L||m+f>P)&&q(),m+=f,a={data:F.compressEvent(a)},b.push(a),(g||{}).n?0===G?q():Q||(Q=d.setTimeout(q,G)):J||(J=d.setTimeout(q,H)),h=!0):h=!1);!h&&c.ue_int&&console.error("Invalid JS Nexus API call");return h}function l(){if(!R){for(var a=0;a<M.length;a++)M[a]();for(a=0;a<I.length;a++)I[a]();b.length&&(c.ue_sbuimp&&c.ue&&c.ue.ssw&&(a=w({dct:h,evt:b}),c.ue.ssw("eeldata",a),c.ue.ssw("eelsts","unk")),u(n._sBcn||{}));R=!0}}function C(a){M.push(a)}
function K(a){I.push(a)}var E=1E3,L=499,P=524288,z=function(){},n=c.ue||{},O=n.log||z,y=c.uex||z;(c.uet||z)("bb","ue_sushi_v1",{wb:1});var f=c.ue_surl||"https://unagi-na.amazon.com/1/events/com.amazon.csm.nexusclient.gamma",v=["messageId","timestamp"],b=[],g={},h={},m=0,A=0,N=0,t=0,M=[],I=[],R=!1,Q,J,G=void 0===c.ue_hpsi?1E3:c.ue_hpsi,H=void 0===c.ue_lpsi?1E4:c.ue_lpsi,F=function(){function a(a){g[a]="#"+A++;h[g[a]]=a;return g[a]}function c(b){if(!(b instanceof Function)){if(b instanceof Array){for(var e=
[],d=b.length,f=0;f<d;f++)e[f]=c(b[f]);return e}if(b instanceof Object){e={};for(d in b)b.hasOwnProperty(d)&&(e[g[d]?g[d]:a(d)]=-1===v.indexOf(d)?c(b[d]):b[d]);return e}return"string"===typeof b&&(b.length>("#"+A).length||"#"===b.charAt(0))?g[b]?g[b]:a(b):b}}return{compressEvent:c,buildPayload:function(){return w({cs:{dct:h},events:b})}}}();(function(){if(n.event&&n.event.isStub){if(c.ue_sbuimp&&c.ue&&c.ue.ssw){var a=c.ue.ssw("eelsts").val;if(a&&"unk"===a&&(a=c.ue.ssw("eeldata").val)){a:{try{var d=
JSON.parse(a);break a}catch(e){}d=null}d&&d.evt instanceof Array&&d.dct instanceof Object&&(b=d.evt,h=d.dct,b&&h&&(q(),c.ue.ssw("eeldata","{}"),c.ue.ssw("eelsts","scs")))}}n.event.replay(function(a){a[3]=a[3]||{};a[3].n=1;D.apply(this,a)});n.onSushiUnload.replay(function(a){C(a[0])});n.onSushiFlush.replay(function(a){K(a[0])})}})();n.attach("beforeunload",l);n.attach("pagehide",l);n._cmps=F;n.event=D;n.event.reset=function(){t=0};n.onSushiUnload=C;n.onSushiFlush=K;try{d.P&&d.P.register&&d.P.register("sushi-client",
z)}catch(a){c.ueLogError(a,{logLevel:"WARN"})}y("ld","ue_sushi_v1",{wb:1})},"Nxs-JS-Client")(ue_csm,window);