(function(m){(function(c){function l(a){return null===a||void 0===a?a:!!a}function y(a,b){if(!b||!b.length)return a;for(var d={},e=0;e<b.length;e++)d[b[e]]=!!a[b[e]];return d}function k(a,b){if(!a&&0!==a)return a;for(var d={},e=0;e<b;e++)d[e+1]=!!(a&1),a>>=1;return d}function z(a){if(a&&a.length){for(var b={},d=0;d<a.length;d++)b[a[d]]=!0;return b}}if(c._has_global("__cmp")||c._has_global("__tcfapi")&&!c._has_global("_adroll_tcfapi_placeholder_installed"))c._install_cmp=function(){};else{c._cmp_calls=
[];c._set_global("__cmp",function(a,b,d){"ping"===a?d({gdprAppliesGlobally:!1,cmpLoaded:!1}):c._cmp_calls.push([a,b,d])});c._tcfapi_calls=[];c._set_global("__tcfapi",function(a,b,d,e){"ping"===a?d({gdprApplies:void 0,cmpLoaded:!1,cmpStatus:"loading",displayStatus:void 0,apiVersion:"2.0",cmpVersion:void 0,cmpId:void 0,gvlVersion:void 0,tcfPolicyVersion:void 0}):c._tcfapi_calls.push([a,e,d])});var m={getVendorConsents:function(a){var b=c._global("__adroll_consent"),d=c._global("__adroll_consent_data"),
e=c._global("__adroll_consent_is_gdpr");d=d.euconsent||"";var h=c.b64toint(d.substr(22,4)),A=c.b64toint(d.substr(26,3))>>2,k={},g={},f,l=c._is_defined;if(a&&a.length)for(f=0;f<a.length;f++)g[a[f]]=l(b[a[f]])?b[a[f]]:null;else{for(f in b)b.hasOwnProperty(f)&&(g[f]=b[f]);for(f=1;f<=A;f++)g[f]=l(b[f])?b[f]:null}for(f=1;24>=f;f++)k[f]=!(isNaN(h)||!(h&1<<24-f));return[{metadata:d.substr(0,18)+d.substr(20,2),gdprApplies:!!e,hasGlobalScope:!1,purposeConsents:k,vendorConsents:g},!0]},getConsentData:function(a){if(a&&
"1.1"!==String(a))return[null,!1];a=c._global("__adroll_consent_data");var b=c._global("__adroll_consent_is_gdpr");return[{consentData:a.euconsent||"",gdprApplies:!!b,hasGlobalScope:!1},!0]},ping:function(){return[{gdprAppliesGlobally:!1,cmpLoaded:!!c._global("__adroll_consent_data").euconsent},!0]}},q=!1,g={},w=0,v={getTCData:function(a){var b=l(c._global("__adroll_consent_is_gdpr")),d=c._global("__adroll_consent_data")||{},e=d.eucookie||{},h=e.publisher_tc||{};d=d.euconsent;var g=e.cmp_id,m=e.cmp_version,
q=l(e.is_service_specific),f=l(e.use_non_standard_stacks),v=e.publisher_iso_country,w=l(e.purpose_one_treatment),B={allowedVendors:z(e.allowed_vendors),disclosedVendors:z(e.disclosed_vendors)},C={consents:k(e.purposes_allowed,24),legitimateInterests:k(e.purposes_li_transparency,24)};a={consents:y(e.vendor_consent,a),legitimateInterests:y(e.vendor_legitimate_interest,a)};var D=k(e.special_feature_opt_ins,12),E=k(h.pub_purposes_consent,24),F=k(h.pub_purposes_li_transparency,24);h={consents:k(h.custom_purposes_consent,
h.num_custom_purposes),legitimateInterests:k(h.custom_purposes_li_transparency,h.num_custom_purposes)};if((e=e.publisher_restrictions)&&"object"===typeof e){var r={};for(n in e)if(e.hasOwnProperty(n)){var p=e[n]||{},t=p.purpose_id,u=p.vendors;p=p.restriction;if(t&&u&&u.length){r[t]=r[t]||{};for(var x=0;x<u.length;x++)r[t][u[x]]=p}}var n=r}else n=void 0;return[{tcString:d,tcfPolicyVersion:2,cmpId:g,cmpVersion:m,gdprApplies:b,cmpStatus:"loaded",isServiceSpecific:q,useNonStandardStacks:f,publisherCC:v,
purposeOneTreatment:w,outOfBand:B,purpose:C,vendor:a,specialFeatureOptins:D,publisher:{consents:E,legitimateInterests:F,customPurpose:h,restrictions:n}},!0]},ping:function(){var a=c._global("__adroll_consent_data"),b=l(c._global("__adroll_consent_is_gdpr"));a=a.eucookie;return[{gdprApplies:b,cmpLoaded:!0,cmpStatus:"loaded",displayStatus:b?"visible":"disabled",apiVersion:"2.0",cmpVersion:a.cmp_version,cmpId:a.cmp_id,gvlVersion:a.vendor_list_version,tcfPolicyVersion:a.tcf_policy_version},!0]},addEventListener:function(a){var b=
++w;g[b]=a;c._dispatch_consent_event(b)},removeEventListener:function(a,b){var d=!1;b in g&&(d=!0,delete g[b]);a(d)}};c._trigger_consent_event=function(){for(var a in g)g.hasOwnProperty(a)&&c._dispatch_consent_event(a)};c._dispatch_consent_event=function(a){if(a in g){var b=g[a],d=v.getTCData(),e="tcloaded",h=c._global("__adroll_consent"),k=c._global("__adroll_consent_banner")||{};null===h||"banner"===k.state?(e="cmpuishown",q=!0):q&&(e="useractioncomplete");d&&2===d.length?(d[0].eventStatus=e,d[0].listenerId=
a,b(d[0],d[1])):b({},!1)}};c._install_cmp=function(){c._set_global("__cmp",function(a,b,c){(a=m[a])&&c.apply(null,a(b))});var a=c._cmp_calls;c._cmp_calls=[];for(var b=0;b<a.length;b++)c._global("__cmp").apply(c,a[b]);c._set_global("__tcfapi",function(a,b,c,g){b=v[a];"addEventListener"===a||"removeEventListener"===a?b.call(null,c,g):c.apply(null,b(g))});a=c._tcfapi_calls||[];c._tcfapi_calls=[];for(b=0;b<a.length;b++)c._global("__tcfapi").apply(c,a[b])}}})(m)})(window.__adroll);
